  name: Java CI with Gradle

  on:
    push:
      branches: [ "main" ]
#    pull_request:
#      branches: [ "main" ]

  jobs:
    build:

      runs-on: ubuntu-latest

      steps:

        - uses: actions/checkout@v3

        - name: Gradle Caching
          uses: actions/cache@v3
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'
#            cache: 'gradle'

#        - name: Login to Docker Hub
#          uses: docker/login-action@v3
#          with:
#            username: ${{ secrets.DOCKERHUB_USERNAME }}
#            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Grant execute permission for gradlew
          run : chmod +x gradlew

#        - run: ./gradlew build --no-daemon
        - run: ./gradlew build

#        - name: Create gradle wrapper
#          run: |
#            ./gradlew wrap

#        - name: Build with jib
#          run: |
#            ./gradlew jib \
#            -Djib.to.image="junhyeoklee/cloud-practice:${GITHUB_REF_NAME}"